// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyColp8JeekY83q-Fv6l2WXdyvpsi4x6oss',
    appId: '1:3136557525:web:ce69a48cecd6bb620f2d5c',
    messagingSenderId: '3136557525',
    projectId: 'goapp-5513d',
    authDomain: 'goapp-5513d.firebaseapp.com',
    storageBucket: 'goapp-5513d.firebasestorage.app',
    measurementId: 'G-Y718HH39Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTgCVlFpf9SqH2wALd1HzRC8Gb3hLBeZI',
    appId: '1:3136557525:android:2dfa13e3626c1efc0f2d5c',
    messagingSenderId: '3136557525',
    projectId: 'goapp-5513d',
    storageBucket: 'goapp-5513d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLd7BaV7wdEEzJDAufFqtP2Cn1k-OgoYA',
    appId: '1:3136557525:ios:21c8fa201a63b2260f2d5c',
    messagingSenderId: '3136557525',
    projectId: 'goapp-5513d',
    storageBucket: 'goapp-5513d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLd7BaV7wdEEzJDAufFqtP2Cn1k-OgoYA',
    appId: '1:3136557525:ios:21c8fa201a63b2260f2d5c',
    messagingSenderId: '3136557525',
    projectId: 'goapp-5513d',
    storageBucket: 'goapp-5513d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyColp8JeekY83q-Fv6l2WXdyvpsi4x6oss',
    appId: '1:3136557525:web:41fde72a93c6c2bf0f2d5c',
    messagingSenderId: '3136557525',
    projectId: 'goapp-5513d',
    authDomain: 'goapp-5513d.firebaseapp.com',
    storageBucket: 'goapp-5513d.firebasestorage.app',
    measurementId: 'G-EJ9C2DJ2VM',
  );
}
